---
# tasks file for ansible-role-snowsql
- name: Download the snowsql
  get_url:
    url: "{{ snowsql_url }}"
    dest: "{{ workspace }}"

- name: Create snowsql installation directory
  file:
    path: "{{ snowsql_install_path }}"
    mode: 0755

- name: Set snowsql path
  lineinfile:
    dest: /etc/profile
    regexp: "{{ item.regexp }}"
    insertafter: EOF
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^export PATH=', line: 'export PATH={{ snowsql_install_path }}:$PATH' }
